### ISSUE TITLE
Umbrella: Support seamless K8s cluster provisioning

### ISSUE THREAD

**Issue by seokho-son** [cloud-barista/cb-tumblebug#1538]
**What would you like to be added**
CB-TB 및 CB-MapUI를 통해서 자유롭게(오류없이) K8s 클러스터를 생성할 수 있는 방안 제공

**Why is this needed**
CB-SP의 각 CSP 드라이버로 CSP K8s 클러스터 서비스를 배포할 수 있는 기능이 제공되고 있으나,
이를 CB-TB를 통해 사용자에게 자유롭게 활용할 수 있게 처리해주기 위해서는
프로비저닝에 활용할 수 있는 가용값(스펙, 이미지, 디스크, k8s버전 등)의 범위를 지정하고 명시할 필요가 있음.
또한 CB-MapUI 등을 통해 쉽게 생성 및 제어를 지원해야 함. 

본 이슈는 우산 이슈이며, 하기 Task를 우선적으로 처리 및 트래킹함. (우선 하나의 CSP가 잘 동작할 수 있도록 처리. CSP 대상 무관)

- [x] #1562
  - 코드상에서 If csp_name 형태의 비교 구문을 활용하지 않고 처리할 수 있도록 처리
  - 신규 csp가 추가되는 경우, 소스코드 수정작업이 없어도 되도록 처리
  - 참고
    - 상기 사항이 고려된 conf: https://github.com/cloud-barista/cb-tumblebug/blob/main/assets/cloudinfo.yaml 
    - viper 처리 방식: https://github.com/cloud-barista/cb-tumblebug/blob/main/src/main.go#L154
  - 업데이트시 기존 기능 문제없는지 확인 필요
- [x] K8s 관련 설정값 추가 및 테스트
- [x] 설정값 조회 기능 개발
- [x] 쿠버네티스용 이미지와 스펙 관리 (assets/cloudspec.csv, assets/cloudimage.csv)
  - Discussion: #1665 
  - PR: #1667 
- [x] 설정값으로 k8s 프로비저닝 관련 요청에 대한 validation 
  - 버전 정보에 대해서 validation 수행
  - PR: #1670
- [x] k8s관련 REST API의 명세에, 구동되는 명확한 예시 지정
  - PR: #1671
- [x] #1583
- [x] CB-MapUI K8s 아이콘 추가, K8s 배포 현황 표기, K8s 접속 방법 제공 등 (assignee: @seokho-son)

**Comment by seokho-son** [comment]
@sykim-etri CB-TB 및 MapUI를 통한 K8s 생성 및 제어 지원 관련하여, 이슈를 생성하였습니다.
주로 요청값에 대한 가용 범위를 conf 를 통해 처리하는 방안에 포커스를 두고 
개선을 진행하면 좋을 것 같습니다. 살펴봐주시길 부탁드립니다. :)

(cc @yunkon-kim)

**Comment by sykim-etri** [comment]
@seokho-son 
`3. 설정값 조회 기능 개발` 항목이 정확하게 의미하는 바가 무엇일까요?

**Comment by seokho-son** [comment]
- ref #1582

**Comment by seokho-son** [comment]
- ref #1614

**Comment by sykim-etri** [comment]
@seokho-son
`k8s관련 REST API의 명세에, 구동되는 명확한 예시 지정` 관련하여 혹시 참고할만한 예시가 있을까요?

**Comment by seokho-son** [comment]
@sykim-etri 

/mcisRecommendVm

와 같이, swagger dashboard에서 바로 실행해볼 수 있도록 예시를 제공하면 되지 않을까요?

각 rest handler function 의 api 주석을 살펴보시면 될 것 같습니다.

**Comment by sykim-etri** [comment]
> @sykim-etri
> 
> /mcisRecommendVm
> 
> 와 같이, swagger dashboard에서 바로 실행해볼 수 있도록 예시를 제공하면 되지 않을까요?
> 
> 각 rest handler function 의 api 주석을 살펴보시면 될 것 같습니다.

REST Handler에서 참조하는 구조체에 example을 좀 더 구체적으로 기재하면 해결될 것 같네요.

**Comment by seokho-son** [comment]
-ref: https://github.com/cloud-barista/cb-tumblebug/releases/tag/v0.9.19 

CB-MapUI K8s 아이콘 추가, K8s 배포 현황 표기

**Comment by seokho-son** [comment]
I think we’ve reached the point. (We still need to keep enhancing it, though.)
